services:
  xenia-backend:
    build:
      context: .
      dockerfile: Docker/Xenia-WebServices/Dockerfile
    environment:
        API_PORT: 36000
        MONGO_URI: mongodb://xenia-database:27017/
        SWAGGER_API: false
    ports:
      - '36000:36000'
    volumes:
      - './Xenia-WebServices/titles:/xenia-web-service/titles'
    depends_on:
      - xenia-database

  xenia-database:
    image: mongo:8
    volumes:
      - 'mongodb-data:/data/db'

  sslv3-proxy:
    build:
      context: .
      dockerfile: Docker/SSLv3Proxy/Dockerfile
    environment:
        LOCAL_FQDN: false
        CLIENT_HOST: 172.17.0.1
    ports:
      - '42127:42127'

volumes:
  mongodb-data:

