services:
  xenia-backend:
    build:
      context: .
      dockerfile: Docker/Xenia-WebServices/Dockerfile
    network_mode: host
    environment:
        API_PORT: 36000
        MONGO_URI: mongodb://127.0.0.1:27017/
        SWAGGER_API: false
    volumes:
      - './Xenia-WebServices/titles:/xenia-web-service/titles'
    depends_on:
      - xenia-database

  xenia-database:
    image: mongo:8
    ports:
      - '27017:27017'
    volumes:
      - 'mongodb-data:/data/db'

volumes:
  mongodb-data:

