services:
  syndicate2012-pse:
    build:
      context: ../..
      dockerfile: Docker/Syndicate2012PSE/Dockerfile
    environment:
        HEADLESS: true
        DISPLAY: $DISPLAY
        WAYLAND_DISPLAY: $WAYLAND_DISPLAY
        XDG_RUNTIME_DIR: $XDG_RUNTIME_DIR
    network_mode: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - '../../ME3Server_WV/bin/Debug/cert:/syndicate2012-pse/cert'
      - '../../ME3Server_WV/bin/Debug/conf:/syndicate2012-pse/conf'
      - '../../ME3Server_WV/bin/Debug/http:/syndicate2012-pse/http'
      - '../../ME3Server_WV/bin/Debug/logs:/syndicate2012-pse/logs'
      - '../../ME3Server_WV/bin/Debug/patch:/syndicate2012-pse/patch'
      - '../../ME3Server_WV/bin/Debug/player:/syndicate2012-pse/player'
      - '../../ME3Server_WV/bin/Debug/replay:/syndicate2012-pse/replay'