name: Test Build Solution

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - uses: nuget/setup-nuget@v1
      with:
        nuget-api-key: ${{ secrets.NuGetAPIKey }}
        nuget-version: '5.x'
      
    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE

    - name: Restore Packages
      run: nuget restore ME3Server_WV.sln

    - name: Build Solution
      run: |
        msbuild.exe ME3Server_WV.sln /nologo /nr:false /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Release"
    
    - name: List Build Directory
      run: dir ME3Server_WV\bin\Release\

    - uses: actions/upload-artifact@v4
      with:
        name: release-build-${{ github.sha }}
        path: ME3Server_WV/bin/Release/
        retention-days: 1
